# Generated by Django 2.1.8 on 2019-12-03 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('add_categories', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='product_base',
            fields=[
                ('base_id', models.AutoField(primary_key=True, serialize=False)),
                ('taged', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('add_product', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('details', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('cover_img', models.ImageField(blank=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillaqui.categories')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='product_base',
            name='detail_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillaqui.product_details'),
        ),
        migrations.AddField(
            model_name='product_base',
            name='prod_cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillaqui.categories'),
        ),
    ]
