# Generated by Django 2.1.8 on 2019-12-27 17:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillaqui', '0004_auto_20191226_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='details',
            field=ckeditor.fields.RichTextField(max_length=49000),
        ),
    ]
