# Generated by Django 2.1.8 on 2019-12-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillaqui', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
